name: TestGithubActionsSecret
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TestGithubActionsSecret
        env:
          SHOGUNCAO_HAVA_A_TEST_SSH_KEY: ${{ secrets.SHOGUNCAO_HAVA_A_TEST_SSH_KEY }}
        run: |
          git clone git@github.com:shoguncao/hava_a_test.sh
        
