name: TestGithubActionsSecret
on:
  push:
  # 1235
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TestGithubActionsSecret
        env:
          SHOGUNCAO_HAVA_A_TEST_SSH_KEY: ${{ secrets.SHOGUNCAO_HAVA_A_TEST_SSH_KEY }}
        run: |
          chmod +x TestGithubActionsSecret.sh
          /bin/bash TestGithubActionsSecret.sh
        
