name: TestGithubActionsSecret
on:
  push:
  # ii
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TestGithubActionsSecret
        env:
          SHOGUNCAO_HAVA_A_TEST_SSH_KEY: ${{ secrets.SHOGUNCAO_HAVA_A_TEST_SSH_KEY }}
        run: |
          echo ${SHOGUNCAO_HAVA_A_TEST_SSH_KEY} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git clone git@github.com:shoguncao/hava_a_test.sh
        
